SEED: 42
DATASET_DIR: "/kaggle/input/datasets/tuyenldvn/falldataset-imvia"
OUTPUT_DIR: "./outputs_fall"

MODEL:
  YOLO_MODEL_NAME: "yolov8m.pt"
  PERSON_CLASS_ID: 0
  SEQ_LEN: 30
  NUM_KEYPOINTS: 33
  FEATURE_DIM: 66
  NUM_CLASSES: 3
  MIN_BBOX_CONF: 0.25
  VISIBILITY_THRESHOLD: 0.0
  MIN_VALID_KEYPOINTS: 10
  WINDOW_STRIDE: 1
  D_MODEL: 128
  NUM_HEADS: 4
  FF_DIM: 256
  NUM_LAYERS: 3
  DROPOUT: 0.3

TRAIN:
  BATCH_SIZE: 64
  EPOCHS: 50
  LEARNING_RATE: 0.001

CLASS_NAMES:
  0: "Normal"
  1: "Falling"
  2: "Lying"
